### ISSUE TITLE
Issue with SessionTokenStore, httpContext is null

### ISSUE THREAD

**Issue by svarukala** [microsoftgraph/msgraph-training-aspnetmvcapp#40]
This issue is not exactly with this sample code but when I extend the code with additional methods, thats when I am seeing the issue with the token store.

I added a new method to upload files to SPO using Microsoft Graph, using the ChunkedUploadProvider which maintains an upload session until the whole file is uploaded. I pasted the method below for your reference.

The code always fails in the method BeforeAccessNotification of SessionTokenStore class with the error:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Here is the line that fails:
args.TokenCache.DeserializeMsalV3((byte[])httpContext.Session[tokenCacheKey]);

The httpContext object is null. 

It appears since the file upload is done asynchronously in separate thread, the httpContext is null. What is the best way to fix this issue? Can we make the SessionTokenStore more robust to handle such scenario?

Here is the file upload method:

        public static async Task<DriveItem> UploadFileAsync(Stream fileStream, string fileName)
        {
            var graphClient = GetAuthenticatedClient();
            DriveItem uploadedFile = null;
            //uploadedFile = await graphClient.Sites["root"].Drive.Root.ItemWithPath(fileName).Content.Request().PutAsync<DriveItem>(fileStream);
            UploadSession uploadSession = null;
            uploadSession = await graphClient.Sites["root"].Drive.Root.ItemWithPath(fileName).CreateUploadSession().Request().PostAsync();

            if (uploadSession != null)
            {
                // Chunk size must be divisible by 320KiB, our chunk size will be slightly more than 1MB
                int maxSizeChunk = (320 * 1024) * 4;
                ChunkedUploadProvider uploadProvider = new ChunkedUploadProvider(uploadSession, graphClient, fileStream, maxSizeChunk);
                var chunkRequests = uploadProvider.GetUploadChunkRequests();
                var exceptions = new List<Exception>();
                var readBuffer = new byte[maxSizeChunk];
                foreach (var request in chunkRequests)
                {
                    var result = await uploadProvider.GetChunkRequestResponseAsync(request, readBuffer, exceptions);

                    if (result.UploadSucceeded)
                    {
                        uploadedFile = result.ItemResponse;
                    }
                }
            }         
            return uploadedFile;
        }

**Comment by svarukala** [comment]
I was able to resolve the issue by using a quick and dirty fix. I used a static HashTable to store the tokenCacheKey (in addition to the httpContext.Session storage). If it helps others, this is what I added to the code:
`private static Hashtable tokenCacheTable = new Hashtable();`

In `private void BeforeAccessNotification(TokenCacheNotificationArgs args)` method I added below line to always retrieve the token cache key from the HashTable instead of httpContext.Session. Also, commented out the rest of the code.
`args.TokenCache.DeserializeMsalV3((byte[])tokenCacheTable[tokenCacheKey]);`

In `private void AfterAccessNotification(TokenCacheNotificationArgs args)` method I added below code to store the token cache key in the hashtable.
```
                    if(!tokenCacheTable.ContainsKey(tokenCacheKey))
                        tokenCacheTable.Add(tokenCacheKey, args.TokenCache.SerializeMsalV3());
```

**Comment by jayendranarumugam** [comment]
Hi @svarukala / @jasonjoh  ,

I'm also facing the same issue after deploying to azure. The code is working in local perfectly but after I deployed into the cloud Its giving object reference not set to an instance (null reference) in the  `args.TokenCache.DeserializeMsalV3((byte[])httpContext.Session[tokenCacheKey]);`

Any idea why it is failing only in an azure web app? and not local

@svarukala could you please provide any workaround?

Thanks in Advance !
Jay

**Comment by svarukala** [comment]
@jayendranarumugam did you try the solution/fix that I mentioned above?

**Comment by jcoenen96** [comment]
@svarukala what happens when the hashtable is empty? Currently our application throws a nullexceptoin due to the fact that session is null. If I replace it with a static hashtable the value is still not set when you access it for the first time, which creates exceptions in GetUsersUniqueId(ClaimsPrincipl user)
